### ISSUE TITLE
Default galaxy base image outdated?

### ISSUE THREAD

**Issue by fishsaidno** [meteor/galaxy-images#5]
Hey!

Seems the `galaxy-app` image hasn't been updated for 3 years (neither here nor Docker hub)?

We're just wanting to run a Meteor app locally (for development, within docker) with the same environment as Galaxy.

Has the base image build for galaxy been moved in-house & we no longer have access to it?
Or are Galaxy apps on Meteor Cloud actually running on this 3 year old image?

Thanks & best regards,

**Comment by filipenevola** [comment]
Hi, on Galaxy developers can use custom images as well.

We are going to update this version soon, probably next week with latest Ubuntu and everything else.

**Comment by filipenevola** [comment]
It's updated now, read more here https://cloud-guide.meteor.com/base-image-packages.html#v2.0
