### ISSUE TITLE
Setting env.TZ no longer sets the timezone on the server

### ISSUE THREAD

**Issue by ecwyne** [meteor/galaxy-images#7]
As of the [Aug 4th image update](https://cloud-guide.meteor.com/base-image-packages.html#v3.0) setting `env.TZ` no longer sets the timezone in my production app.

**Comment by renanccastro** [comment]
Hi, @ecwyne. Can you please reach us out at support@meteor.com informing your app so we can check more details?

I couldn't repro the issue you are talking about, for example, using the following code:

```js
    console.log(process.env.TZ);
    const d = new Date();
    console.log(d.toLocaleTimeString());
    console.log(""+d)
```

in an app that is set with its settings.json as: 

```json
	"galaxy.meteor.com": {
		"env": {
			"TZ": "America/Bogota",
		}

```

I have the following output:

```
2021-08-06 19:17:04-03:00 America/Bogota
2021-08-06 19:17:04-03:00 5:17:04 PM
2021-08-06 19:17:04-03:00 Fri Aug 06 2021 17:17:04 GMT-0500 (Colombia Standard Time)
```

I'm closing it here as the repro is not easy, but we can keep talking in a ticket!
